config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end


  get  'orders/thanks',to: "orders#thanks"

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :orders,  only: [:index, :create, :show, :new]
  post 'orders/confirm',to: "orders#confirm"



  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#destroy_all'

  resources :items, only: [:index, :show]

  namespace :admin do
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

  namespace :admin do
    get 'homes/top'
  end

  namespace :admin do
   resources :customers, only: [:index,:show,:edit,:update]
  end

  # get 'customers/show', to: "customers#show", as: 'my_page'

  resource :customers, only: [:edit,:update]
  get 'customers/my_page', to: 'customers#show'
  patch 'customers/my_page', to: 'customers#show'
  get'customers/quit'
  patch 'customers/out',to: "customers#out"


  root to: 'homes#top'
  get 'homes/about'


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code, :residence, :phone_number, :email, :is_valid)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
      customers_my_page_path
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

  before_action :reject_inactive_customer, only: [:create]

  protected

  def reject_inactive_customer

    @customer = Customer.find_by(email: params[:customer][:email])
      if @customer == nil || @customer.is_valid == false
        redirect_to new_customer_session_path
      end

  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
   @customer = current_customer
  end

  def edit
   @customer = current_customer
  end

  def update
   @customer = current_customer
   @customer.update(customer_params)
   redirect_to customers_my_page_path
  end

  def quit
  end
  def out
   @customer = current_customer
   @customer.update(is_valid: false)
   reset_session
   redirect_to root_path
  end

end

private


def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code, :residence, :phone_number, :email,)
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-offset-1 col-xs-8">
		<h4 class=" my-4"><spna><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</span></h4>
		<%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
		<table width="700" height="400">
	  <tbody>
	    <tr>
      <td class="info col-xs-2">会員ID</td>
      <td><%= @customer.id %></td>
     </tr>
     <tr>
      <td class="info col-xs-2">氏名</td>
      <td><%= f.text_field :first_name %>　　<%= f.text_field :last_name %></td>
     </tr>
     <tr>
      <td class="info col-xs-2">フリガナ</td>
      <td><%= f.text_field :kana_first_name %>　　<%= f.text_field :kana_last_name %></td>
     </tr>
     <tr>
      <td class="info col-xs-2">郵便番号</td>
      <td><%= f.text_field :postal_code %></td>
     </tr>
     <tr>
      <td class="info col-xs-2">住所</td>
      <td><%= f.text_field :residence, size: 50 %></td>
     </tr><tr>
      <td class="info col-xs-2">電話番号</td>
      <td><%= f.text_field :phone_number %></td>
     </tr>
     <tr>
      <td class="info col-xs-2">メールアドレス</td>
      <td><%= f.email_field :email %></td>
     </tr>
     <tr>
      <td class="info col-xs-2">会員ステータス</td>
      <td>
           <%= f.radio_button :is_valid, :true %>有効
           <%= f.radio_button :is_valid, :false %>退会
      </td>
     </tr>
     <tr>
      <td class="info col-xs-2"></td>
      <td> <%= f.submit '変更を保存',class:"btn btn-success" %></td>
      <td> </td>
     </tr>
    </tbody>
    </table>
     <% end %>

  </div>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="row">
<div class="offset-3">
  <h3 class="mt-3"><span>会員一覧</span></h3>
  <table class="table table-bord" >
	<tbody>
    <tr>
	   <th>会員ID</th>
		 <th>氏名</th>
		 <th>メールアドレス</th>
		 <th>ステータス</th>
		<tr>
	 <% @customers.each do |customer| %>
	  <tr>
      <td><%= customer.id %></td>
	   	<td>
	   		<%= link_to admin_customer_path(customer) do %>
	   		<%= customer.first_name %><%= customer.last_name %>
	   		<% end %>
	    </td>
		  <td><%= customer.email %></td>
		  <td>
			<% if customer.is_valid %>
			<p class="text-success">有効</p>
			<% else %>
			<p class="text-danger">退会</p>
			<% end %>
		  </td>
     </tr>
     <% end %>
	</tbody>
  </table>
</div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
<div class="row">
<div class="col-xs-offset-1 col-xs-8">
  <h4 class="head-line  title_h2 my-5"><span><%= @customer.first_name %><%= @customer.last_name %>の会員詳細</span></h4>
  <table width="700" height="350" >
	<tbody class="offset-1">
     	<tr>
				<td width="30%">会員ID</td>
        <td width="70%"><%= @customer.id %></td>
			</tr>
			<tr>
				<td>氏名</td>
        <td><%= @customer.first_name %> <%= @customer.last_name %></td>
			</tr>
			<tr>
				<td>フリガナ</td>
        <td><%= @customer.kana_first_name %> <%= @customer.kana_last_name %></td>
			</tr>
			<tr>
				<td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
			</tr>
			<tr>
				<td>住所</td>
        <td><%= @customer.residence %> </td>
			</tr>
			<tr>
				<td>電話番号</td>
        <td><%= @customer.phone_number %> </td>
			</tr>
			<tr>
				<td>メールアドレス</td>
        <td><%= @customer.email %> </td>
			</tr>
			<tr>
				<td>会員ステータス</td>
        <td>
        	<% if @customer.is_valid %>
			     <p class="text-success">有効</p>
			    <% else %>
			     <p class="text-danger">退会</p>
			    <% end %>
        </td>
			</tr>
			<tr>
        <td></td>
        <td><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>　　　　<%= link_to "注文一覧を見る", customers_quit_path, class: "btn btn-primary" %></td>
     </tr>
	</tbody>
  </table>