config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end


  get  'orders/thanks',to: "orders#thanks"

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :orders,  only: [:index, :create, :show, :new]
  post 'orders/confirm',to: "orders#confirm"



  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#destroy_all'

  resources :items, only: [:index, :show]

  namespace :admin do
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

  namespace :admin do
    get 'homes/top'
  end

  namespace :admin do
   resources :customers, only: [:index,:show,:edit,:update]
  end

  # get 'customers/show', to: "customers#show", as: 'my_page'

  resource :customers, only: [:edit,:update]
  get 'customers/my_page', to: 'customers#show'
  patch 'customers/my_page', to: 'customers#show'
  get'customers/quit'
  patch 'customers/out',to: "customers#out"


  root to: 'homes#top'
  get 'homes/about'


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
 enum status: { payment_waiting: 0, payment_confirmation: 1, production: 2, preparation: 3, sent: 4 }
 enum payment_method: { credit_card: 0, transfer: 1 }
 belongs_to :customer
 has_many :order_details, dependent: :destroy

 def personal_information
    self.postal_code + self.address + self.name
 end

 validates :customer_id, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :name, presence: true
 validates :postage, presence: true
 validates :total_payment, presence: true
 validates :payment_method, presence: true
 validates :status, presence: true



end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      # binding.pry
      @order.order_details.update(making_status:1) if @order.status == "payment_confirmation"
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @cart_items = current_customer.cart_items
  end

  def create
    @order = Order.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items
    @cart_items.each do |cart_item|
    order_detail = OrderDetail.new(item_id: cart_item.item_id,order_id: @order.id,price: cart_item.item.with_tax_price,amount: cart_item.amount,making_status: 0)
    order_detail.save
    end
    current_customer.cart_items.destroy_all
    redirect_to orders_thanks_path
  end

  def confirm
    @cart_items = current_customer.cart_items
    @order = Order.new
    if params[:order][:payment_method] == "0"
      @order.payment_method = 0
    else
      @order.payment_method = 1
    end
    if params[:order][:address_option]  == "0"
       @order.postal_code = current_customer.postal_code
       @order.address = current_customer.residence
       @order.name = current_customer.first_name + current_customer.last_name
    elsif params[:order][:address_option] == "1"
       @address = Address.find(params[:order][:address_id])
       @order.postal_code = @address.postal_code
       @order.address = @address.address
       @order.name = @address.name
    else
      @order.postal_code =  params[:order][:postal_code]
      @order.address =  params[:order][:address]
      @order.name =  params[:order][:name]
    end
    @postage = 800
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @postage = 800
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :postage, :total_payment, :payment_method, :status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/show.html.erb
<h4 class="my-4"><span>注文履歴詳細</span></h4>
<table>
  <tr>
    <th>購入者</th>
    <td><%= @order.customer.first_name %><%= @order.customer.last_name %></td>
  </tr>
  <tr>
    <th>注文日</th>
    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>配送先</th>
    <td><%= @order.address %></td>
  </tr>
  <tr>
    <th>支払方法</th>
    <td><%= @order.payment_method_i18n %></td>
  </tr>
  <tr>
    <th>注文ステータス</th>
    <td>
      <%= form_with model: @order,url: admin_order_path,  local:true do |f| %>
      <%#= f.select :status, [["入金待ち", "0" ], ["入金確認", "1"], ["発送準備中", "2" ], ["製作中", "3" ], ["発送済", "4" ]] %>
      <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, selected: @order.status %>
      <%= f.submit '更新', class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
</table>
<div class="row mt-4">
  <table border="1" width="800" height="auto">
      <tr>
  	   <th>商品名</th>
  		 <th>単価（税込）</th>
  		 <th>数量</th>
  		 <th>小計</th>
  		 <th>制作ステータス</th>
  		<tr>
  		<% @order.order_details.each do |order_details| %>
  	  <tr>
        <td><%= order_details.item.name %></td>
  	   	<td><%= order_details.item.with_tax_price %></td>
  		  <td><%= order_details.amount %></td>
  		  <td><%= order_details.amount * order_details.price%></td>
  		  <td><%= form_with model: order_details,url: admin_order_detail_path(order_details.id), local:true do |f| %>
            <%#= f.select :making_status, [["制作不可", "制作不可"], ["制作待ち", "制作待ち"], ["制作中", "制作中"], ["制作完了", "制作完了"]] %>
            <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, selected: order_details.making_status %>
            <%= f.submit '更新', class: "btn btn-success" %>
            <% end %>

  		  </td>
       </tr>
      <% end %>
   </table>
   <table class="offset-1">
    <tr>
      <th>商品合計</th>
      <td><%= @order.total_payment %></td>
    </tr>
    <tr>
      <th>送料</th>
      <td><%= @postage %></td>
    </tr>
    <tr>
      <th>請求金額合計</th>
      <td><%= @order.total_payment + @postage %></td>
    </tr>
   </table>
 </div>