config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end


  get  'orders/thanks',to: "orders#thanks"

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  resources :orders,  only: [:index, :create, :show, :new]
  post 'orders/confirm',to: "orders#confirm"



  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#destroy_all'

  resources :items, only: [:index, :show]

  namespace :admin do
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

  namespace :admin do
    get 'homes/top'
  end

  namespace :admin do
   resources :customers, only: [:index,:show,:edit,:update]
  end

  # get 'customers/show', to: "customers#show", as: 'my_page'

  resource :customers, only: [:edit,:update]
  get 'customers/my_page', to: 'customers#show'
  patch 'customers/my_page', to: 'customers#show'
  get'customers/quit'
  patch 'customers/out',to: "customers#out"


  root to: 'homes#top'
  get 'homes/about'


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


  def personal_information
    self.postal_code + self.address + self.name
  end

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :customer
   belongs_to :item


   def subtotal
       item.with_tax_price * amount
   end

   validates :item_id, presence: true
   validates :customer_id, presence: true
   validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image

  def with_tax_price
      (price * 1.1).floor
  end

  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
 enum status: { payment_waiting: 0, payment_confirmation: 1, production: 2, preparation: 3, sent: 4 }
 enum payment_method: { credit_card: 0, transfer: 1 }
 belongs_to :customer
 has_many :order_details, dependent: :destroy

 def personal_information
    self.postal_code + self.address + self.name
 end

 validates :customer_id, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :name, presence: true
 validates :postage, presence: true
 validates :total_payment, presence: true
 validates :payment_method, presence: true
 validates :status, presence: true



end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

   enum making_status: { production_impossible: 0, production_wait: 1, production: 2, produced: 3 }
   belongs_to :item
   belongs_to :order

   validates :item_id, presence: true
   validates :order_id, presence: true
   validates :price, presence: true
   validates :amount, presence: true
   validates :making_status, presence: true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
   @address = Address.new
   @addresses = current_customer.addresses
  end

  def create
  @address = Address.new(address_params)
  @address.customer_id = current_customer.id
  @address.save
  redirect_to addresses_path
  end

  def edit
  @address = Address.find(params[:id])
  end

  def update
  @address = Address.find(params[:id])
  @address.update(address_params)
  redirect_to addresses_path
  end

  def destroy
  @address = Address.find(params[:id])
  @address.destroy
  redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:customer_id, :name, :postal_code, :address )
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
   @customer = current_customer
  end

  def edit
   @customer = current_customer
  end

  def update
   @customer = current_customer
   @customer.update(customer_params)
   redirect_to customers_my_page_path
  end

  def quit
  end
  def out
   @customer = current_customer
   @customer.update(is_valid: false)
   reset_session
   redirect_to root_path
  end

end

private


def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :postal_code, :residence, :phone_number, :email,)
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
   @items = Item.all
  end

  def show
   @item = Item.find(params[:id])
   @cart_item = CartItem.new
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image_id, :introduction, :price, :is_active)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @cart_items = current_customer.cart_items
  end

  def create
    @order = Order.new(order_params)
    @order.save
    @cart_items = current_customer.cart_items
    @cart_items.each do |cart_item|
    order_detail = OrderDetail.new(item_id: cart_item.item_id,order_id: @order.id,price: cart_item.item.with_tax_price,amount: cart_item.amount,making_status: 0)
    order_detail.save
    end
    current_customer.cart_items.destroy_all
    redirect_to orders_thanks_path
  end

  def confirm
    @cart_items = current_customer.cart_items
    @order = Order.new
    if params[:order][:payment_method] == "0"
      @order.payment_method = 0
    else
      @order.payment_method = 1
    end
    if params[:order][:address_option]  == "0"
       @order.postal_code = current_customer.postal_code
       @order.address = current_customer.residence
       @order.name = current_customer.first_name + current_customer.last_name
    elsif params[:order][:address_option] == "1"
       @address = Address.find(params[:order][:address_id])
       @order.postal_code = @address.postal_code
       @order.address = @address.address
       @order.name = @address.name
    else
      @order.postal_code =  params[:order][:postal_code]
      @order.address =  params[:order][:address]
      @order.name =  params[:order][:name]
    end
    @postage = 800
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @postage = 800
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :postage, :total_payment, :payment_method, :status)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/itmes_helper.rb
module ItmesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column vh-100 ">
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark p-4 border-bottom border-secondary">
    <div class="container">
      <a class=" btn btn-outline-dark" href="/"><h2>LOGO</h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
         <% if customer_signed_in? %>
          <li><%= link_to "マイページ", customers_my_page_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "商品一覧", items_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "カート", cart_items_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, class:"btn btn-outline-dark" %></li>
          <% elsif admin_signed_in? %>
          <li><%= link_to "商品一覧", admin_items_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "会員一覧",  admin_customers_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "注文履歴一覧",  admin_homes_top_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, class:"btn btn-outline-dark" %></li>
          <% else %>
          <li><%= link_to "About", homes_about_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "商品一覧", homes_about_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "新規登録", new_customer_registration_path, class:"btn btn-outline-dark" %></li>
          <li><%= link_to "ログイン", new_customer_session_path, class:"btn btn-outline-dark" %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
  </header>
   <main>
     <div class="container mx-auto">
       <%= yield %>
     </div>
   </main>

  <footer class="fixed-bottom">

  </footer>
 </body>
</html>